const COLOR_AZUL_OSCURO = '#25233C';
const COLOR_AZUL_CLARO = '#0096FF';
const COLOR_BLANCO = '#FFF';
const COLOR_NEGRO = '#434349';
const COLOR_GRIS_CLARO = '#EAEDF7';
const COLOR_VERDE_CLARO = '#6AFCA8';
const COLOR_GRIS = "#E3E3E3E3";
const COLOR_PURPURA = '#6259CA';
const COLOR_GRIS_OSCURO = '#484756';
const COLOR_CELESTE = '#8FB8F7';
const COLOR_ROJO = '#DD1144';
const COLOR_VERDE_BRILLANTE = '#1EFD42';


export {
  COLOR_AZUL_OSCURO,
  COLOR_AZUL_CLARO,
  COLOR_BLANCO,
  COLOR_NEGRO,
  COLOR_GRIS_CLARO,
  COLOR_VERDE_CLARO,
  COLOR_PURPURA,
  COLOR_GRIS_OSCURO,
  COLOR_GRIS,
  COLOR_CELESTE,
  COLOR_ROJO,
  COLOR_VERDE_BRILLANTE
};